[package]
name = "mathstack"
version = "0.1.0"
authors = ["mpd <mpd@jesters-court.net>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_consume = "1.0.6"
enum_dispatch = "0.3.4"
lazy_static = "1.4.0"