[package]
name = "lpc-rs"
version = "0.1.0"
authors = ["mpd <mpd@jesters-court.net>"]
edition = "2021"

[build-dependencies]
lalrpop = "0.19.4"

[dependencies]
arrayvec = "0.7.1"
auto_impl = "0.4.1"
bstr = "0.2.17"
cached = "0.24.0"
codespan-reporting = "0.11.0"
decorum = "0.3.1"
delegate = "0.6.1"
enum_dispatch = "0.3.4"
fs-err = "2.6.0"
if_chain = "1.0.1"
indextree = "4.3.1"
itertools = "0.10.0"
lalrpop-util = "0.19.4"
lazy_format = "1.8.4"
lazy_static = "1.4.0"
logos = "0.12.0"
modular-bitfield = "0.11.2"
multimap = "0.8.2"
parking_lot = "0.11.1"
path-absolutize = { version = "3.0.6", features = ["lazy_static_cache"] }
phf = { version = "0.10.0", features = ["macros"] }
refpool = "0.4.3"
regex = "1"
rmp-serde = "0.15.4"
rustyline = "8.2.0" # lpcdb only
serde = { version = "1.0.123", features = ["derive", "rc"] }
serde_derive = "1.0.123"
toml = "0.5.8"

[dev-dependencies]
indoc = "1.0"