[package]
name = "lpc-rs-function-support"
description = "lpc-rs LPC compiler and gamedriver suite function support."
version = "0.1.0"
authors = ["mpd <mpd@jesters-court.net>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/xxx/lpc-rs"
license = "MIT"
keywords = ["lpc", "mud", "driver", "compiler"]
categories = ["command-line-utilities", "compilers", "game-engines"]

[dependencies]
lpc-rs-asm = { version = "0.1", path = "../lpc-rs-asm" }
lpc-rs-core = { version = "0.1", path = "../lpc-rs-core" }
lpc-rs-errors = { version = "0.1", path = "../lpc-rs-errors" }
lpc-rs-utils = { version = "0.1", path = "../lpc-rs-utils" }

derive_builder = "0.20.2"
itertools = "0.15.0"
readonly = "0.2.3"
tracing = "~0.1"

[dev-dependencies]
ustr = "1.1.0"
