[package]
name = "lpc-rs-errors"
description = "lpc-rs LPC compiler and gamedriver suite error support."
version = "0.1.0"
authors = ["mpd <mpd@jesters-court.net>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/xxx/lpc-rs"
license = "MIT"
keywords = ["lpc", "mud", "driver", "compiler"]
categories = ["command-line-utilities", "compilers", "game-engines"]

[dependencies]
codespan-reporting = "0.13.1"
derive_builder = "0.20.2"
lalrpop-util = "0.23.1"
parking_lot = "0.12.0"
