pub mod function_flags;
pub mod function_prototype;
pub mod program_function;
pub mod local_scope;
pub mod lpc_type;
pub mod lpc_type_union;
pub mod scope_tree;
pub mod semantic_checks;
pub mod symbol;
