use std::collections::HashMap;

use multimap::MultiMap;

use tree_walker::TreeWalker;

use crate::{
    asm::{
        instruction::{Address, Instruction},
        register::Register,
        register_counter::RegisterCounter,
    },
    ast::{
        array_node::ArrayNode,
        assignment_node::AssignmentNode,
        ast_node::{AstNode, AstNodeTrait, SpannedNode},
        binary_op_node::{BinaryOpNode, BinaryOperation},
        block_node::BlockNode,
        call_node::CallNode,
        decl_node::DeclNode,
        expression_node::ExpressionNode,
        float_node::FloatNode,
        function_def_node::FunctionDefNode,
        if_node::IfNode,
        int_node::IntNode,
        mapping_node::MappingNode,
        program_node::ProgramNode,
        range_node::RangeNode,
        return_node::ReturnNode,
        string_node::StringNode,
        unary_op_node::{UnaryOpNode, UnaryOperation},
        var_init_node::VarInitNode,
        var_node::VarNode,
        while_node::WhileNode,
    },
    codegen::{tree_walker, tree_walker::ContextHolder},
    context::Context,
    errors::LpcError,
    interpreter::{efun::EFUN_PROTOTYPES, program::Program},
    parser::span::Span,
    semantic::{function_symbol::FunctionSymbol, lpc_type::LpcType, symbol::Symbol},
    Result,
};

use crate::{
    ast::{
        do_while_node::DoWhileNode, for_node::ForNode, function_def_node::ARGV,
        ternary_node::TernaryNode,
    },
    interpreter::efun::{CALL_OTHER, CATCH},
};
use std::rc::Rc;

macro_rules! push_instruction {
    ($slf:expr, $inst:expr, $span:expr) => {
        $slf.instructions.push($inst);
        $slf.debug_spans.push($span);
    };
}

const CREATE_FUNCTION: &str = "create";

/// Partition on whether the value is stored in registers or memory, to help select instructions.
/// tl;dr - Value types use `Register`, while reference types use `Memory`.
enum OperationType {
    Register,
    Memory,
}

/// A tree walker that generates assembly language instructions based on an AST.
#[derive(Debug, Default)]
pub struct CodegenWalker {
    /// The vector of instructions generated by this walker
    pub instructions: Vec<Instruction>,

    /// Code [`Span`]s, corresponding to the instructions, for use in runtime error messaging
    debug_spans: Vec<Option<Span>>,

    /// The map of labels, to their respective addresses
    pub labels: HashMap<String, Address>,

    /// counter for labels, as they need to be unique.
    label_count: usize,

    /// The map of function Symbols, to their respective addresses
    pub functions: HashMap<Rc<FunctionSymbol>, Address>,

    /// Track where the result of a child branch is
    current_result: Register,

    /// The internal counter to track which registers are used.
    register_counter: RegisterCounter,

    /// The counter for tracking globals
    global_counter: RegisterCounter,

    /// The number of [`Register`]s needed for global initialization
    global_init_registers: usize,

    /// The compilation context
    context: Context,
}

impl CodegenWalker {
    /// Create a new [`CodegenWalker`] that consumes the passed scopes
    ///
    /// # Arguments
    /// `context` - The [`Context`] state that this tree walker will use for its internal workings.
    pub fn new(context: Context) -> Self {
        Self {
            context,
            ..Self::default()
        }
    }

    /// Get a listing of a translated AST, suitable for printing
    ///
    /// # Examples
    /// ```
    /// use lpc_rs::ast::binary_op_node::{BinaryOpNode, BinaryOperation};
    /// use lpc_rs::ast::int_node::IntNode;
    /// use lpc_rs::ast::expression_node::ExpressionNode;
    /// use lpc_rs::codegen::codegen_walker::CodegenWalker;
    /// use lpc_rs::codegen::tree_walker::TreeWalker;
    ///
    /// let mut node = BinaryOpNode {
    ///     l: Box::new(ExpressionNode::Int(IntNode::new(123))),
    ///     r: Box::new(ExpressionNode::Int(IntNode::new(456))),
    ///     op: BinaryOperation::Sub,
    ///     span: None
    /// };
    /// let mut walker = CodegenWalker::default();
    ///
    /// walker.visit_binary_op(&mut node);
    ///
    /// for instruction in walker.listing() {
    ///     println!("{}", instruction);
    /// }
    /// ```
    pub fn listing(&self) -> Vec<String> {
        let mut v = vec![];

        // invert these maps for by-address lookup
        let functions_by_pc = self
            .functions
            .values()
            .zip(self.functions.keys())
            .collect::<HashMap<_, _>>();

        // use MultiMap as multiple labels can be at the same address
        let labels_by_pc = self
            .labels
            .values()
            .zip(self.labels.keys())
            .collect::<MultiMap<_, _>>();

        for (counter, instruction) in self.instructions.iter().enumerate() {
            if let Some(sym) = functions_by_pc.get(&counter) {
                v.push(format!(
                    "fn {} num_args={} num_locals={}:",
                    sym.name, sym.num_args, sym.num_locals
                ));
            }
            if let Some(vec) = labels_by_pc.get_vec(&counter) {
                for label in vec {
                    v.push(format!("{}:", label));
                }
            }
            v.push(format!("    {}", instruction));
        }

        v
    }

    /// Return a map of function names to their corresponding full symbol
    pub fn function_map(&self) -> HashMap<String, Rc<FunctionSymbol>> {
        let mut map = HashMap::new();

        for sym in self.functions.keys() {
            map.insert(sym.name.clone(), sym.clone());
        }

        map
    }

    /// Convert this walker's data into a [`Program`]
    pub fn to_program(&self) -> Result<Program> {
        // These are expected and assumed to be in 1:1 correspondence at runtime
        self.ensure_sync()?;

        Ok(Program {
            instructions: self.instructions.clone(),
            debug_spans: self.debug_spans.clone(),
            filename: self.context.filename.clone(),
            labels: self.labels.clone(),
            functions: self.function_map(),
            // add +1 to num_globals for r0, for call return values
            num_globals: self.global_counter.as_usize() + 1,
            num_init_registers: self.register_counter.as_usize(),
            pragmas: self.context.pragmas.clone(),
        })
    }

    fn ensure_sync(&self) -> Result<()> {
        let a = self.instructions.len();
        let b = self.debug_spans.len();

        if a != b {
            return Err(LpcError::new(format!(
                "Instructions (length {}) and `debug_spans` (length {}) are out \
                        of sync. This would be catastrophic at runtime, and indicates \
                        a major bug in the code generator.",
                a, b
            )));
        }

        Ok(())
    }

    /// Get a reference to a symbol in the current scope
    fn lookup_symbol(&self, name: &str) -> Option<&Symbol> {
        self.context.scopes.lookup(name)
    }

    /// Get a mutable reference to a symbol in the current scope
    fn lookup_symbol_mut(&mut self, name: &str) -> Option<&mut Symbol> {
        self.context.scopes.lookup_mut(name)
    }

    /// Check for a symbol in the global scope
    fn lookup_global(&self, name: &str) -> Option<&Symbol> {
        self.context.scopes.lookup_global(name)
    }

    /// encapsulate vars that can find themselves if they're global
    fn lookup_var_symbol(&self, node: &VarNode) -> Option<&Symbol> {
        if node.global {
            self.lookup_global(&node.name)
        } else {
            self.lookup_symbol(&node.name)
        }
    }

    /// helper to choose operation instructions
    fn to_operation_type(&self, node: &ExpressionNode) -> OperationType {
        match node {
            ExpressionNode::Int(_) |
            ExpressionNode::Float(_) => OperationType::Register,

            ExpressionNode::String(_) |
            ExpressionNode::Array(_) |
            ExpressionNode::Mapping(_) |
            // TODO: Calls can be optimized if we can get the return types available here
            ExpressionNode::Call(_) |
            ExpressionNode::CommaExpression(_) |
            ExpressionNode::Range(_) => OperationType::Memory,
            ExpressionNode::Assignment(node) => self.to_operation_type(&node.lhs),
            ExpressionNode::BinaryOp(node) => {
                let left_type = self.to_operation_type(&node.l);
                let right_type = self.to_operation_type(&node.r);
                match (left_type, right_type) {
                    (OperationType::Register, OperationType::Register) => OperationType::Register,
                    _ => OperationType::Memory,
                }
            }
            ExpressionNode::Ternary(node) => {
                let body_type = self.to_operation_type(&node.body);
                let else_type = self.to_operation_type(&node.else_clause);
                match (body_type, else_type) {
                    (OperationType::Register, OperationType::Register) => OperationType::Register,
                    _ => OperationType::Memory,
                }
            }
            ExpressionNode::UnaryOp(node) => {
                let expr_type = self.to_operation_type(&node.expr);

                if matches!(expr_type, OperationType::Register) {
                    OperationType::Register
                } else {
                    OperationType::Memory
                }
            }
            ExpressionNode::Var(v) => {
                match self.lookup_var_symbol(v) {
                    Some(Symbol { type_: ty, .. }) => {
                        match ty {
                            LpcType::Int(false) => OperationType::Register,
                            LpcType::Float(false) => OperationType::Register,
                            _ => OperationType::Memory,
                        }
                    }
                    None => OperationType::Memory // arbitrary - doing this instead of panicking
                }
            }
        }
    }

    /// The main switch to determine which instruction we select for a binary operation
    fn choose_op_instruction(
        &self,
        node: &BinaryOpNode,
        reg_left: Register,
        reg_right: Register,
        reg_result: Register,
    ) -> Instruction {
        match node.op {
            BinaryOperation::Add => self.choose_num_or_mixed(
                node,
                || Instruction::IAdd(reg_left, reg_right, reg_result),
                || Instruction::MAdd(reg_left, reg_right, reg_result),
            ),
            BinaryOperation::Sub => self.choose_num_or_mixed(
                node,
                || Instruction::ISub(reg_left, reg_right, reg_result),
                || Instruction::MSub(reg_left, reg_right, reg_result),
            ),
            BinaryOperation::Mul => self.choose_num_or_mixed(
                node,
                || Instruction::IMul(reg_left, reg_right, reg_result),
                || Instruction::MMul(reg_left, reg_right, reg_result),
            ),
            BinaryOperation::Div => Instruction::IDiv(reg_left, reg_right, reg_result),
            BinaryOperation::Mod => Instruction::IMod(reg_left, reg_right, reg_result),
            BinaryOperation::Index => Instruction::Load(reg_left, reg_right, reg_result),
            BinaryOperation::AndAnd => Instruction::AndAnd(reg_left, reg_right, reg_result),
            BinaryOperation::OrOr => Instruction::OrOr(reg_left, reg_right, reg_result),
            BinaryOperation::Or => Instruction::Or(reg_left, reg_right, reg_result),
            BinaryOperation::EqEq => Instruction::EqEq(reg_left, reg_right, reg_result),
            BinaryOperation::Lt => Instruction::Lt(reg_left, reg_right, reg_result),
            BinaryOperation::Lte => Instruction::Lte(reg_left, reg_right, reg_result),
            BinaryOperation::Gt => Instruction::Gt(reg_left, reg_right, reg_result),
            BinaryOperation::Gte => Instruction::Gte(reg_left, reg_right, reg_result),
        }
    }

    /// Allows for recursive determination of typed binary operator instructions, allowing
    /// choice between a numeric (i.e. held in registers) and mixed (i.e. tracked via references)
    /// Switching on the instructions lets us avoid some value lookups at runtime.
    fn choose_num_or_mixed<F, G>(&self, node: &BinaryOpNode, a: F, b: G) -> Instruction
    where
        F: Fn() -> Instruction,
        G: Fn() -> Instruction,
    {
        let left_type = self.to_operation_type(&node.l);
        let right_type = self.to_operation_type(&node.r);

        match (left_type, right_type) {
            (OperationType::Register, OperationType::Register) => a(),
            _ => b(),
        }
    }

    /// A special case for function def parameters, where we don't want to generate code
    /// for default arguments - we just want to have it on hand to refer to
    /// when we generate code for calls.
    fn visit_parameter(&mut self, node: &VarInitNode) {
        self.assign_sym_location(&node.name)
    }

    /// A helper to assign the next free [`Register`] to a [`Symbol`]
    /// of the given name, within the current scope.
    fn assign_sym_location(&mut self, name: &str) {
        let current_register = self.register_counter.next().unwrap();

        let symbol = self.lookup_symbol_mut(name);
        if let Some(sym) = symbol {
            sym.location = Some(current_register);
        }
    }

    /// Emit the instruction(s) to take the range of an array or string
    /// # Arguments
    /// `reference` - The [`Register`] holding the reference to the ref we're taking a slice from.
    /// `node` - A reference to the [`RangeNode`] that holds the range of the slice we're taking.
    fn emit_range(&mut self, reference: Register, node: &mut RangeNode) -> Result<()> {
        let first_index = if let Some(expr) = &mut *node.l {
            expr.visit(self)?;
            self.current_result
        } else {
            // Default to 0. No instruction needed as the value in registers defaults to int 0.
            self.register_counter.next().unwrap()
        };

        let second_index = if let Some(expr) = &mut *node.r {
            expr.visit(self)?;
            self.current_result
        } else {
            // A missing range end means just go to the end of the array.
            let register = self.register_counter.next().unwrap();
            let instruction = Instruction::IConst(register, -1);
            self.instructions.push(instruction);
            self.debug_spans.push(node.span);
            register
        };

        let result = self.register_counter.next().unwrap();
        self.current_result = result;
        self.instructions.push(Instruction::Range(
            reference,
            first_index,
            second_index,
            result,
        ));
        self.debug_spans.push(node.span);

        Ok(())
    }

    /// Emit a numbered label with prefix `T`, tracking the current count.
    fn new_label<T>(&mut self, prefix: T) -> String
    where
        T: AsRef<str>,
    {
        let r = format!("{}_{}", prefix.as_ref(), self.label_count);
        self.label_count += 1;
        r
    }

    // special case for `catch()`
    fn emit_catch(&mut self, node: &mut CallNode) -> Result<()> {
        let result_register = self.register_counter.next().unwrap();
        let label = self.new_label("catch_end");

        push_instruction!(
            self,
            Instruction::CatchStart(result_register, label.clone()),
            node.span
        );

        for argument in &mut node.arguments {
            argument.visit(self)?;
        }

        // get the address of the `catchend` pseudo-instruction, so we can jump to a location
        // that is both guaranteed to have an instruction, as well as clean up the handled
        // catch point
        let label_address = self.instructions.len();
        self.labels.insert(label, label_address);

        push_instruction!(self, Instruction::CatchEnd, node.span);

        self.current_result = result_register;

        Ok(())
    }
}

impl ContextHolder for CodegenWalker {
    fn into_context(self) -> Context {
        self.context
    }
}

impl TreeWalker for CodegenWalker {
    fn visit_program(&mut self, program: &mut ProgramNode) -> Result<()> {
        self.context.scopes.goto_root();

        // Partition global variable initializations vs everything else
        let (global_init, functions): (Vec<&mut AstNode>, Vec<&mut AstNode>) = program
            .body
            .iter_mut()
            .partition(|x| matches!(**x, AstNode::Decl(_)));

        // Hoist all global variables, and initialize them at the very start of the program
        for node in global_init {
            node.visit(self).unwrap();
        }

        if self
            .context
            .function_prototypes
            .contains_key(CREATE_FUNCTION)
        {
            let mut call = CallNode {
                receiver: Box::new(None),
                arguments: vec![],
                name: "create".to_string(),
                span: None,
            };
            call.visit(self)?;
        }

        let mut ret = ReturnNode {
            value: None,
            span: None,
        };
        ret.visit(self)?;

        for node in functions {
            node.visit(self)?;
        }

        self.context.scopes.pop();

        Ok(())
    }

    fn visit_block(&mut self, node: &mut BlockNode) -> Result<()> {
        self.context.scopes.goto(node.scope_id);

        for stmt in &mut node.body {
            stmt.visit(self)?;
        }

        self.context.scopes.pop();
        Ok(())
    }

    fn visit_call(&mut self, node: &mut CallNode) -> Result<()> {
        if node.name == CATCH {
            return self.emit_catch(node);
        }

        let mut arg_results = Vec::new();
        let mut ellipsis_results = Vec::new();
        let default_params = self.context.default_function_params.get(&node.name);
        let mut ellipsis = false;

        // All "normal" functions should have a set of default params to match the declared params,
        // even if the defaults are all `None`.
        if let Some(function_args) = default_params {
            // TODO: get rid of this clone or make it cheaper
            let mut function_args = function_args.clone();

            // generate code for the explicitly-specified arguments
            for (idx, function_arg) in function_args.iter_mut().enumerate() {
                // use passed parameters, or default parameters if applicable.
                if let Some(arg) = node.arguments.get_mut(idx) {
                    arg.visit(self)?;
                    arg_results.push(self.current_result);
                } else if let Some(arg) = function_arg {
                    arg.visit(self)?;
                    arg_results.push(self.current_result);
                }
            }

            // generate code for ellipsis arguments
            if let Some(prototype) = self.context.function_prototypes.get(&node.name) {
                if prototype.flags.ellipsis() {
                    ellipsis = true;
                    let ellipsis_arg_count =
                        node.arguments.len().saturating_sub(function_args.len());

                    if ellipsis_arg_count > 0 {
                        let ellipsis_args = &mut node.arguments[function_args.len()..];

                        ellipsis_results.reserve_exact(ellipsis_arg_count);

                        for arg in ellipsis_args {
                            arg.visit(self)?;
                            ellipsis_results.push(self.current_result);
                        }
                    }
                }
            }

            if ellipsis {
                let mut argv = match self.context.scopes.function_scope_mut(&node.name) {
                    Some(scope) => match scope.lookup_mut(ARGV) {
                        Some(sym) => sym,
                        None => {
                            return Err(LpcError::new(
                                    "Ellipsis args were passed, but cannot find `argv`'s location. This should not happen."
                                ).with_span(node.span));
                        }
                    },
                    None => {
                        return Err(LpcError::new(
                            "Ellipsis args were passed, but cannot find `argv`'s location. This should not happen."
                        ).with_span(node.span));
                    }
                };

                let current_register = self.register_counter.next().unwrap();
                argv.location = Some(current_register);

                self.current_result = current_register;
                push_instruction!(
                    self,
                    Instruction::AConst(current_register, ellipsis_results),
                    node.span
                );
                arg_results.push(current_register);
            }
        } else {
            // TODO: This is where efuns are handled
            for argument in &mut node.arguments {
                argument.visit(self)?;
                arg_results.push(self.current_result);
            }
        }

        let instruction = if arg_results.len() == 1 {
            // no need to serialize args for the `Call` instruction if there's only one.
            if let Some(rcvr) = &mut *node.receiver {
                rcvr.visit(self)?;
                let receiver_result = self.current_result;
                let name_register = self.register_counter.next().unwrap();
                push_instruction!(
                    self,
                    Instruction::SConst(name_register, node.name.clone()),
                    node.span
                );

                Instruction::CallOther {
                    receiver: receiver_result,
                    name: name_register,
                    num_args: arg_results.len(),
                    initial_arg: arg_results[0],
                }
            } else {
                Instruction::Call {
                    name: node.name.clone(),
                    num_args: arg_results.len(),
                    initial_arg: arg_results[0],
                }
            }
        } else {
            let start_register = self.register_counter.next().unwrap();
            let mut register = start_register;

            // copy each result to the start of the arg register
            for result in &arg_results {
                push_instruction!(self, Instruction::RegCopy(*result, register), node.span);
                register = self.register_counter.next().unwrap();
            }

            // Undo the final call to .next() in the above for-loop to avoid wasting a register
            self.register_counter.go_back();

            if let Some(rcvr) = &mut *node.receiver {
                rcvr.visit(self)?;
                let receiver_result = self.current_result;

                let name_register = self.register_counter.next().unwrap();
                push_instruction!(
                    self,
                    Instruction::SConst(name_register, node.name.clone()),
                    node.span
                );

                Instruction::CallOther {
                    receiver: receiver_result,
                    name: name_register,
                    num_args: arg_results.len(),
                    initial_arg: start_register,
                }
            } else if node.name == CALL_OTHER {
                let receiver = arg_results[0];
                let name = arg_results[1];

                Instruction::CallOther {
                    receiver,
                    name,
                    num_args: arg_results.len() - 2,
                    initial_arg: if arg_results.len() > 2 {
                        arg_results[2]
                    } else {
                        arg_results[0] // i.e. no args used in the function
                    },
                }
            } else {
                Instruction::Call {
                    name: node.name.clone(),
                    num_args: arg_results.len(),
                    initial_arg: start_register,
                }
            }
        };

        self.instructions.push(instruction);
        self.debug_spans.push(node.span);

        // Take care of the result after the call returns.
        if let Some(func) = self.context.function_prototypes.get(&node.name) {
            if func.return_type == LpcType::Void {
                self.current_result = Register(0);
            } else {
                let next_register = self.register_counter.next().unwrap();

                push_instruction!(
                    self,
                    Instruction::RegCopy(Register(0), next_register),
                    node.span()
                );

                self.current_result = next_register;
            }
        } else if let Some(func) = EFUN_PROTOTYPES.get(node.name.as_str()) {
            if func.return_type == LpcType::Void {
                self.current_result = Register(0);
            } else {
                let next_register = self.register_counter.next().unwrap();

                push_instruction!(
                    self,
                    Instruction::RegCopy(Register(0), next_register),
                    node.span()
                );

                self.current_result = next_register;
            }
        } else if node.receiver.is_some() {
            let next_register = self.register_counter.next().unwrap();

            push_instruction!(
                self,
                Instruction::RegCopy(Register(0), next_register),
                node.span()
            );

            self.current_result = next_register;
        } else {
            return Err(LpcError::new(format!(
                "Unable to find return type for `{}`. This is a weird issue that indicates \
                something very broken in the semantic checks.",
                node.name
            ))
            .with_span(node.span));
        }

        Ok(())
    }

    fn visit_int(&mut self, node: &mut IntNode) -> Result<()> {
        let register = self.register_counter.next().unwrap();
        self.current_result = register;
        let instruction = match node.value {
            0 => Instruction::IConst0(register),
            1 => Instruction::IConst1(register),
            v => Instruction::IConst(register, v),
        };
        push_instruction!(self, instruction, node.span);

        Ok(())
    }

    fn visit_float(&mut self, node: &mut FloatNode) -> Result<()> {
        let register = self.register_counter.next().unwrap();
        self.current_result = register;
        let instruction = Instruction::FConst(self.current_result, node.value);
        push_instruction!(self, instruction, node.span);

        Ok(())
    }

    fn visit_string(&mut self, node: &mut StringNode) -> Result<()> {
        let register = self.register_counter.next().unwrap();
        self.current_result = register;

        push_instruction!(
            self,
            Instruction::SConst(register, node.value.clone()),
            node.span
        );

        Ok(())
    }

    fn visit_binary_op(&mut self, node: &mut BinaryOpNode) -> Result<()> {
        node.l.visit(self)?;
        let reg_left = self.current_result;

        // Ranges need special handling that complicates this function otherwise, due to
        // the visit to node.r needing to handle multiple results.
        if node.op == BinaryOperation::Index {
            if let ExpressionNode::Range(range_node) = &mut *node.r {
                self.emit_range(reg_left, range_node)?;
                return Ok(());
            }
        }

        node.r.visit(self)?;
        let reg_right = self.current_result;

        let reg_result = self.register_counter.next().unwrap();
        self.current_result = reg_result;

        let instruction = self.choose_op_instruction(node, reg_left, reg_right, reg_result);
        push_instruction!(self, instruction, node.span);

        Ok(())
    }

    fn visit_unary_op(&mut self, node: &mut UnaryOpNode) -> Result<()> {
        node.expr.visit(self)?;
        let reg_expr = self.current_result;

        self.current_result = match node.op {
            UnaryOperation::Negate => {
                // multiply by -1
                let reg = self.register_counter.next().unwrap();
                let instruction = Instruction::IConst(reg, -1);
                push_instruction!(self, instruction, node.span);

                let reg_result = self.register_counter.next().unwrap();

                let instruction = Instruction::MMul(reg_expr, reg, reg_result);
                push_instruction!(self, instruction, node.span);

                reg_result
            }
            UnaryOperation::Inc => todo!(),
            UnaryOperation::Dec => todo!(),
            UnaryOperation::Bang => {
                let reg_result = self.register_counter.next().unwrap();

                let instruction = Instruction::Not(reg_expr, reg_result);
                push_instruction!(self, instruction, node.span);

                reg_result
            }
            UnaryOperation::Tilde => todo!(),
        };

        Ok(())
    }

    fn visit_function_def(&mut self, node: &mut FunctionDefNode) -> Result<()> {
        let return_address = self.instructions.len();

        let len = self.instructions.len();
        self.context.scopes.goto_function(&node.name)?;
        self.register_counter.push(0);

        for parameter in &node.parameters {
            self.visit_parameter(parameter);
        }

        if node.flags.ellipsis() {
            self.assign_sym_location(ARGV);
        }

        for expression in &mut node.body {
            expression.visit(self)?;
        }

        // insert a final return if one isn't already there.
        if self.instructions.len() == len
            || (!self.instructions.is_empty()
                && *self.instructions.last().unwrap() != Instruction::Ret)
        {
            // TODO: This should emit a warning unless the return type is void
            push_instruction!(self, Instruction::Ret, node.span);
        }

        self.context.scopes.pop();

        let num_args = node.parameters.len() + (node.flags.ellipsis() as usize);

        self.functions.insert(
            Rc::new(FunctionSymbol {
                name: node.name.clone(),
                num_args,
                num_locals: self.register_counter.as_usize() - num_args,
                address: return_address,
            }),
            return_address,
        );

        self.register_counter.pop();

        Ok(())
    }

    fn visit_return(&mut self, node: &mut ReturnNode) -> Result<()> {
        if let Some(expression) = &mut node.value {
            expression.visit(self)?;
            let copy = Instruction::RegCopy(self.current_result, Register(0));
            push_instruction!(self, copy, expression.span());
        }

        push_instruction!(self, Instruction::Ret, node.span);

        Ok(())
    }

    fn visit_decl(&mut self, node: &mut DeclNode) -> Result<()> {
        for init in &mut node.initializations {
            self.visit_var_init(init)?;
        }

        Ok(())
    }

    fn visit_var_init(&mut self, node: &mut VarInitNode) -> Result<()> {
        let current_register;
        let symbol = self.lookup_symbol(&node.name);

        let sym = match symbol {
            Some(s) => s,
            None => {
                return Err(LpcError::new(format!(
                    "Missing symbol, that somehow passed semantic checks?: {}",
                    node.name
                ))
                .with_span(node.span))
            }
        };

        let global = sym.is_global();

        current_register = if let Some(expression) = &mut node.value {
            expression.visit(self)?;

            if matches!(expression, ExpressionNode::Var(_)) {
                // Copy to a new register so the new var isn't literally
                // sharing a register with the old one.
                let next_register = self.register_counter.next().unwrap();
                push_instruction!(
                    self,
                    Instruction::RegCopy(self.current_result, next_register),
                    node.span()
                );
                next_register
            } else {
                self.current_result
            }
        } else {
            // Default value to 0 when uninitialized.
            self.register_counter.next().unwrap()
        };

        if global {
            // Store the reference in the globals register.
            // Using next() means global r0 is never used,
            // but makes it possible to skip a bunch of conditionals.
            let dest_register = self.global_counter.next().unwrap();
            let instruction = Instruction::GStore(current_register, dest_register);
            self.global_init_registers = current_register.index();
            push_instruction!(self, instruction, node.span);
        }

        let current_global_register = self.global_counter.current();
        let symbol = self.lookup_symbol_mut(&node.name);

        if let Some(sym) = symbol {
            if global {
                sym.location = Some(current_global_register);
            } else {
                sym.location = Some(current_register);
            }
        }

        Ok(())
    }

    fn visit_var(&mut self, node: &mut VarNode) -> Result<()> {
        let sym = match self.lookup_var_symbol(node) {
            Some(s) => s,
            None => {
                return Err(
                    LpcError::new(format!("Unable to find symbol `{}`", node.name))
                        .with_span(node.span),
                );
            }
        };

        let sym_loc = match sym.location {
            Some(l) => l,
            None => {
                return Err(
                    LpcError::new(format!("Symbol `{}` has no location set.", sym.name))
                        .with_span(node.span),
                );
            }
        };

        if sym.is_global() {
            let result_register = self.register_counter.next().unwrap();
            let instruction = Instruction::GLoad(sym_loc, result_register);
            push_instruction!(self, instruction, node.span);

            self.current_result = result_register;
        } else {
            self.current_result = sym_loc;
        }

        Ok(())
    }

    fn visit_assignment(&mut self, node: &mut AssignmentNode) -> Result<()> {
        node.rhs.visit(self)?;
        let rhs_result = self.current_result;
        let lhs = &mut *node.lhs;

        if matches!(lhs, ExpressionNode::Var(_)) {
            lhs.visit(self)?;
        }

        match lhs {
            ExpressionNode::Var(VarNode { name, global, .. }) => {
                let lhs_result = self.current_result;

                let assign = Instruction::RegCopy(rhs_result, lhs_result);

                push_instruction!(self, assign, node.span);

                // Copy over globals if necessary
                if *global {
                    if let Some(Symbol {
                        scope_id: 0,
                        location: Some(register),
                        ..
                    }) = self.lookup_global(name)
                    {
                        let store = Instruction::GStore(lhs_result, *register);
                        push_instruction!(self, store, node.span);
                    }
                }

                self.current_result = lhs_result;
            }
            ExpressionNode::BinaryOp(BinaryOpNode {
                op: BinaryOperation::Index,
                ref mut l,
                ref mut r,
                ..
            }) => {
                l.visit(self)?;
                let var_result = self.current_result;
                r.visit(self)?;
                let index_result = self.current_result;

                let store = Instruction::Store(rhs_result, var_result, index_result);

                push_instruction!(self, store, node.span);

                self.current_result = rhs_result;
            }
            x => {
                return Err(LpcError::new(format!(
                    "Attempt to assign to an invalid lvalue: `{}`",
                    x
                ))
                .with_span(node.span))
            }
        }

        Ok(())
    }

    fn visit_array(&mut self, node: &mut ArrayNode) -> Result<()> {
        let mut items = Vec::with_capacity(node.value.len());
        for member in &mut node.value {
            let _ = member.visit(self);
            items.push(self.current_result);
        }

        let register = self.register_counter.next().unwrap();
        self.current_result = register;
        push_instruction!(self, Instruction::AConst(register, items), node.span);

        Ok(())
    }

    fn visit_mapping(&mut self, node: &mut MappingNode) -> Result<()> {
        let mut map = HashMap::new();
        for (key, value) in &mut node.value {
            key.visit(self)?;
            let key_result = self.current_result;
            value.visit(self)?;

            map.insert(key_result, self.current_result);
        }

        let register = self.register_counter.next().unwrap();
        self.current_result = register;
        push_instruction!(self, Instruction::MapConst(register, map), node.span);

        Ok(())
    }

    fn visit_if(&mut self, node: &mut IfNode) -> Result<()> {
        self.context.scopes.goto(node.scope_id);
        let else_label = self.new_label("if-else");
        let end_label = self.new_label("if-end");

        // Visit the condition
        node.condition.visit(self)?;

        // If the condition is false (i.e. equal to 0 or 0.0), jump to the end of the "then" body.
        // Insert a placeholder address, which we correct below after the body's code is generated
        let instruction = Instruction::Jz(self.current_result, else_label.clone());
        push_instruction!(self, instruction, node.span);

        // Generate the main body of the statement
        node.body.visit(self)?;

        if node.else_clause.is_some() {
            let instruction = Instruction::Jmp(end_label.clone());
            push_instruction!(self, instruction, node.span);
        }

        let addr = self.instructions.len();
        self.labels.insert(else_label, addr);

        // Generate the else clause code if necessary
        if let Some(n) = &mut *node.else_clause {
            n.visit(self)?;

            let addr = self.instructions.len();
            self.labels.insert(end_label, addr);
        }

        self.context.scopes.pop();
        Ok(())
    }

    fn visit_while(&mut self, node: &mut WhileNode) -> Result<()> {
        self.context.scopes.goto(node.scope_id);

        let start_label = self.new_label("while-start");
        let end_label = self.new_label("while-end");
        let start_addr = self.instructions.len();
        self.labels.insert(start_label.clone(), start_addr);

        node.condition.visit(self)?;

        let cond_result = self.current_result;

        let instruction = Instruction::Jz(cond_result, end_label.clone());
        push_instruction!(self, instruction, node.span);

        node.body.visit(self)?;

        // go back to the start of the loop
        let instruction = Instruction::Jmp(start_label);
        push_instruction!(self, instruction, node.span);

        let addr = self.instructions.len();
        self.labels.insert(end_label, addr);

        self.context.scopes.pop();
        Ok(())
    }

    fn visit_do_while(&mut self, node: &mut DoWhileNode) -> Result<()> {
        self.context.scopes.goto(node.scope_id);

        let start_label = self.new_label("do-while-start");
        let start_addr = self.instructions.len();
        self.labels.insert(start_label.clone(), start_addr);

        node.body.visit(self)?;
        node.condition.visit(self)?;

        // Go back to the start of the loop if the result isn't zero
        let instruction = Instruction::Jnz(self.current_result, start_label);
        push_instruction!(self, instruction, node.span);

        self.context.scopes.pop();
        Ok(())
    }

    fn visit_for(&mut self, node: &mut ForNode) -> Result<()> {
        self.context.scopes.goto(node.scope_id);

        if let Some(i) = &mut *node.initializer {
            i.visit(self)?;
        }

        let start_label = self.new_label("for-start");
        let end_label = self.new_label("for-end");
        let start_addr = self.instructions.len();
        self.labels.insert(start_label.clone(), start_addr);

        if let Some(cond) = &mut node.condition {
            cond.visit(self)?;

            let instruction = Instruction::Jz(self.current_result, end_label.clone());
            push_instruction!(self, instruction, cond.span());
        };

        node.body.visit(self)?;

        if let Some(i) = &mut node.incrementer {
            i.visit(self)?;
        }

        // go back to the start of the loop
        let instruction = Instruction::Jmp(start_label);
        push_instruction!(self, instruction, node.span);

        let addr = self.instructions.len();
        self.labels.insert(end_label, addr);

        self.context.scopes.pop();
        Ok(())
    }

    fn visit_ternary(&mut self, node: &mut TernaryNode) -> Result<()> {
        let result_reg = self.register_counter.next().unwrap();
        let else_label = self.new_label("ternary-else");
        let end_label = self.new_label("ternary-end");

        node.condition.visit(self)?;

        let instruction = Instruction::Jz(self.current_result, else_label.clone());
        push_instruction!(self, instruction, node.span);

        node.body.visit(self)?;
        push_instruction!(
            self,
            Instruction::RegCopy(self.current_result, result_reg),
            node.span
        );

        let instruction = Instruction::Jmp(end_label.clone());
        push_instruction!(self, instruction, node.span);

        let else_addr = self.instructions.len();
        self.labels.insert(else_label, else_addr);

        node.else_clause.visit(self)?;
        push_instruction!(
            self,
            Instruction::RegCopy(self.current_result, result_reg),
            node.span
        );

        let end_addr = self.instructions.len();
        self.labels.insert(end_label, end_addr);

        self.current_result = result_reg;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        asm::instruction::Instruction::{
            AConst, Call, GLoad, GStore, IAdd, IConst, IConst0, IConst1, RegCopy, Ret, SConst,
            Store,
        },
        ast::{
            ast_node::AstNode, comma_expression_node::CommaExpressionNode,
            expression_node::ExpressionNode,
        },
        codegen::scope_walker::ScopeWalker,
        lpc_parser,
        parser::{
            lexer::{LexWrapper, TokenVecWrapper},
            span::Span,
        },
        semantic::lpc_type::LpcType,
        LpcFloat,
    };

    use super::*;
    use crate::{asm::instruction::Address, compiler::Compiler};

    fn walk_prog(prog: &str) -> CodegenWalker {
        let compiler = Compiler::default();
        let mut scope_walker = ScopeWalker::new(Context::default());
        let (code, preprocessor) = compiler.preprocess_string("foo.c", prog).unwrap();

        let context = preprocessor.into_context();
        let mut tree = lpc_parser::ProgramParser::new()
            .parse(&context, TokenVecWrapper::new(&code))
            .unwrap();

        let _ = scope_walker.visit_program(&mut tree);
        let context = scope_walker.into_context();

        let mut walker = CodegenWalker::new(context);
        let _ = tree.visit(&mut walker);

        walker
    }

    fn generate_instructions(prog: &str) -> Vec<Instruction> {
        walk_prog(prog).instructions
    }

    mod test_visit_program {
        use super::*;
        use crate::asm::instruction::Instruction::MAdd;

        #[test]
        fn populates_the_instructions() {
            let prog = "
                void create() {
                    1 + 3 - 5;
                    dump(4 + 5);
                }
            ";

            let instructions = generate_instructions(prog);

            let expected = vec![
                Call {
                    name: String::from("create"),
                    num_args: 0,
                    initial_arg: Register(1),
                },
                Ret,
                IConst(Register(1), -1),
                IConst(Register(2), 9),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(2),
                },
                Ret, // Automatically added due to no explicit return
            ];

            assert_eq!(instructions, expected);
        }

        #[test]
        fn initializes_the_globals() {
            let prog = r#"
                int j = 123;
                string q = "cool";
                void marf() {
                    dump(q + j);
                }
            "#;

            let instructions = generate_instructions(prog);

            let expected = [
                IConst(Register(1), 123),
                GStore(Register(1), Register(1)),
                SConst(Register(2), String::from("cool")),
                GStore(Register(2), Register(2)),
                Ret, // return from global init. if create() is defined, we just continue on to it
                GLoad(Register(2), Register(1)),
                GLoad(Register(1), Register(2)),
                MAdd(Register(1), Register(2), Register(3)),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(3),
                },
                Ret,
            ];

            assert_eq!(instructions, expected);
        }

        #[test]
        fn calls_create_if_create_is_defined() {
            let prog = r#"
                int q = 666;
                int marf() {
                    return 3;
                }
                void create() {
                    dump(marf() + " times a winner!");
                }
            "#;

            let instructions = generate_instructions(prog);

            let expected = [
                IConst(Register(1), 666),
                GStore(Register(1), Register(1)),
                Call {
                    name: String::from("create"),
                    num_args: 0,
                    initial_arg: Register(2),
                },
                Ret, // end of initialization
                IConst(Register(1), 3),
                RegCopy(Register(1), Register(0)),
                Ret, // end of marf()
                Call {
                    name: String::from("marf"),
                    num_args: 0,
                    initial_arg: Register(1),
                },
                RegCopy(Register(0), Register(1)),
                SConst(Register(2), String::from(" times a winner!")),
                MAdd(Register(1), Register(2), Register(3)),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(3),
                },
                Ret, // end of create()
            ];

            assert_eq!(instructions, expected);
        }

        #[test]
        fn tracks_global_registers_over_multiple_sections() {
            let prog = r#"
                int q = 666;
                int marf() {
                    return 3;
                }
                int r = 777;
            "#;

            let instructions = generate_instructions(prog);

            let expected = [
                IConst(Register(1), 666),
                GStore(Register(1), Register(1)),
                IConst(Register(2), 777),
                GStore(Register(2), Register(2)),
                Ret,
                IConst(Register(1), 3),
                RegCopy(Register(1), Register(0)),
                Ret,
            ];

            assert_eq!(instructions, expected);
        }
    }

    mod test_visit_call {
        use crate::asm::instruction::Instruction::{Call, CallOther, IDiv, CatchEnd, CatchStart};

        use super::*;
        use crate::semantic::{
            function_flags::FunctionFlags, function_prototype::FunctionPrototype,
        };

        #[test]
        fn populates_the_instructions() {
            let mut walker = CodegenWalker::default();
            let call = "dump(4 - 5)";
            let mut tree = lpc_parser::CallParser::new()
                .parse(&Context::default(), LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                IConst(Register(1), -1),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn populates_the_instructions_for_call_other() {
            let mut walker = CodegenWalker::default();
            let call = "\"foo\"->print(4 - 5)";
            let mut tree = lpc_parser::ExpressionParser::new()
                .parse(&Context::default(), LexWrapper::new(call))
                .unwrap();

            let _ = tree.visit(&mut walker);

            let expected = vec![
                IConst(Register(1), -1),
                SConst(Register(2), String::from("foo")),
                SConst(Register(3), String::from("print")),
                CallOther {
                    receiver: Register(2),
                    name: Register(3),
                    num_args: 1,
                    initial_arg: Register(1),
                },
                RegCopy(Register(0), Register(4)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn populates_the_instructions_for_catch() {
            let mut walker = CodegenWalker::default();
            let call = "catch(12 / 0)";
            let mut tree = lpc_parser::ExpressionParser::new()
                .parse(&Context::default(), LexWrapper::new(call))
                .unwrap();

            let _ = tree.visit(&mut walker);

            let expected = vec![
                CatchStart(Register(1), "catch_end_0".into()),
                IConst(Register(2), 12),
                IConst0(Register(3)),
                IDiv(Register(2), Register(3), Register(4)),
                CatchEnd
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn populates_the_instructions_with_defaults() {
            let mut default_function_params = HashMap::new();

            default_function_params.insert(
                String::from("foo"),
                vec![None, Some(ExpressionNode::from("muffuns"))],
            );

            let context = Context {
                default_function_params,
                ..Context::default()
            };

            let mut walker = CodegenWalker::new(context);
            let call = "foo(666)";
            let mut tree = lpc_parser::CallParser::new()
                .parse(&walker.context, LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                IConst(Register(1), 666),
                SConst(Register(2), String::from("muffuns")),
                RegCopy(Register(1), Register(3)),
                RegCopy(Register(2), Register(4)),
                Call {
                    name: "foo".to_string(),
                    num_args: 2,
                    initial_arg: Register(3),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn copies_non_void_call_results() {
            let mut context = Context::default();
            let prototype = FunctionPrototype {
                name: "marfin".into(),
                return_type: LpcType::Int(false),
                num_args: 1,
                num_default_args: 0,
                arg_types: vec![],
                span: None,
                arg_spans: vec![],
                flags: FunctionFlags::default(),
            };

            context
                .function_prototypes
                .insert("marfin".into(), prototype);
            let mut walker = CodegenWalker::new(context);
            let call = "marfin(666)";
            let mut tree = lpc_parser::CallParser::new()
                .parse(&walker.context, LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                IConst(Register(1), 666),
                Call {
                    name: String::from("marfin"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
                RegCopy(Register(0), Register(2)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn does_not_copy_void_call_results() {
            let mut context = Context::default();
            let prototype = FunctionPrototype {
                name: "void_thing".into(),
                return_type: LpcType::Void,
                num_args: 1,
                num_default_args: 0,
                arg_types: vec![],
                span: None,
                arg_spans: vec![],
                flags: FunctionFlags::default(),
            };

            context
                .function_prototypes
                .insert("void_thing".into(), prototype);
            let mut walker = CodegenWalker::new(context);
            let call = "void_thing(666)";
            let mut tree = lpc_parser::CallParser::new()
                .parse(&walker.context, LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                IConst(Register(1), 666),
                Call {
                    name: String::from("void_thing"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn copies_non_void_efun_results() {
            let mut walker = CodegenWalker::default();
            let call = r#"clone_object("/foo.c")"#;
            let mut tree = lpc_parser::CallParser::new()
                .parse(&Context::default(), LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                SConst(Register(1), String::from("/foo.c")),
                Call {
                    name: String::from("clone_object"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
                RegCopy(Register(0), Register(2)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn does_not_copy_void_efun_results() {
            let mut walker = CodegenWalker::default();
            let call = r#"dump("lkajsdflkajsdf")"#;
            let mut tree = lpc_parser::CallParser::new()
                .parse(&Context::default(), LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                SConst(Register(1), String::from("lkajsdflkajsdf")),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn handles_ellipsis_functions() {
            let mut context = Context::default();
            let prototype = FunctionPrototype {
                name: "my_func".into(),
                return_type: LpcType::Void,
                num_args: 1,
                num_default_args: 0,
                arg_types: vec![LpcType::String(false)],
                span: None,
                arg_spans: vec![],
                flags: FunctionFlags::default().with_ellipsis(true),
            };

            context
                .function_prototypes
                .insert("my_func".into(), prototype);
            let mut walker = CodegenWalker::new(context);
            let call = "my_func(\"hello!\", 42, \"cool beans\")";
            let mut tree = lpc_parser::CallParser::new()
                .parse(&walker.context, LexWrapper::new(call))
                .unwrap();

            let _ = walker.visit_call(&mut tree);

            let expected = vec![
                SConst(Register(1), "hello!".into()),
                IConst(Register(2), 42),
                SConst(Register(3), "cool beans".into()),
                RegCopy(Register(1), Register(4)),
                RegCopy(Register(2), Register(5)),
                RegCopy(Register(3), Register(6)),
                Call {
                    name: "my_func".into(),
                    num_args: 3,
                    initial_arg: Register(4),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    #[test]
    fn test_visit_int_populates_the_instructions() {
        let mut walker = CodegenWalker::default();

        let mut tree = IntNode::new(666);
        let mut tree0 = IntNode::new(0);
        let mut tree1 = IntNode::new(1);

        let _ = walker.visit_int(&mut tree);
        let _ = walker.visit_int(&mut tree0);
        let _ = walker.visit_int(&mut tree1);

        let expected = vec![
            IConst(Register(1), 666),
            IConst0(Register(2)),
            IConst1(Register(3)),
        ];

        assert_eq!(walker.instructions, expected);
    }

    mod test_binary_op {
        use crate::asm::instruction::Instruction::{FConst, IConst0, IMul, Load, MAdd, Range};

        use super::*;

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_ints() {
            let mut walker = CodegenWalker::default();

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::Int(IntNode::new(666))),
                r: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::Int(IntNode::new(123))),
                    r: Box::new(ExpressionNode::Int(IntNode::new(456))),
                    op: BinaryOperation::Add,
                    span: None,
                })),
                op: BinaryOperation::Mul,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                IConst(Register(1), 666),
                IConst(Register(2), 123),
                IConst(Register(3), 456),
                IAdd(Register(2), Register(3), Register(4)),
                IMul(Register(1), Register(4), Register(5)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_floats() {
            let mut context = Context::default();
            context.scopes.push_new();
            let mut sym = Symbol::new("foo", LpcType::Float(false));
            sym.location = Some(Register(1));
            context.scopes.current_mut().unwrap().insert(sym);

            let mut walker = CodegenWalker::new(context);

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::Float(FloatNode::new(123.45))),
                r: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::Var(VarNode {
                        name: "foo".to_string(),
                        span: None,
                        global: false,
                    })),
                    r: Box::new(ExpressionNode::Int(IntNode::new(456))),
                    op: BinaryOperation::Mul,
                    span: None,
                })),
                op: BinaryOperation::Add,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                FConst(Register(1), LpcFloat::from(123.45)),
                GLoad(Register(1), Register(2)),
                IConst(Register(3), 456),
                IMul(Register(2), Register(3), Register(4)),
                IAdd(Register(1), Register(4), Register(5)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_strings() {
            let mut walker = CodegenWalker::default();

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::String(StringNode::new("foo"))),
                r: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::String(StringNode::new("bar"))),
                    r: Box::new(ExpressionNode::String(StringNode::new("baz"))),
                    op: BinaryOperation::Add,
                    span: None,
                })),
                op: BinaryOperation::Add,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                SConst(Register(1), String::from("foo")),
                SConst(Register(2), String::from("bar")),
                SConst(Register(3), String::from("baz")),
                MAdd(Register(2), Register(3), Register(4)),
                MAdd(Register(1), Register(4), Register(5)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_arrays() {
            let mut walker = CodegenWalker::default();

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::from(vec![ExpressionNode::from(123)])),
                r: Box::new(ExpressionNode::from(vec![ExpressionNode::from(456)])),
                op: BinaryOperation::Add,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                IConst(Register(1), 123),
                AConst(Register(2), vec![Register(1)]),
                IConst(Register(3), 456),
                AConst(Register(4), vec![Register(3)]),
                MAdd(Register(2), Register(4), Register(5)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_indexes() {
            let context = Context::default();
            let mut walker = CodegenWalker::new(context);

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::from(vec![ExpressionNode::from(123)])),
                r: Box::new(ExpressionNode::from(0)),
                op: BinaryOperation::Index,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                IConst(Register(1), 123),
                AConst(Register(2), vec![Register(1)]),
                IConst0(Register(3)),
                Load(Register(2), Register(3), Register(4)),
            ];

            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_binary_op_populates_the_instructions_for_slices() {
            let mut walker = CodegenWalker::default();

            let mut node = BinaryOpNode {
                l: Box::new(ExpressionNode::from(vec![ExpressionNode::from(123)])),
                r: Box::new(ExpressionNode::Range(RangeNode {
                    l: Box::new(Some(ExpressionNode::from(1))),
                    r: Box::new(None),
                    span: None,
                })),
                op: BinaryOperation::Index,
                span: None,
            };

            let _ = walker.visit_binary_op(&mut node);

            let expected = vec![
                IConst(Register(1), 123),
                AConst(Register(2), vec![Register(1)]),
                IConst1(Register(3)),
                IConst(Register(4), -1),
                Range(Register(2), Register(3), Register(4), Register(5)),
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    #[test]
    fn test_visit_string_populates_the_instructions() {
        let mut walker = CodegenWalker::default();
        let mut node = StringNode::new("marf");
        let mut node2 = StringNode::new("tacos");
        let mut node3 = StringNode::new("marf");

        let _ = walker.visit_string(&mut node);
        let _ = walker.visit_string(&mut node2);
        let _ = walker.visit_string(&mut node3);

        let expected = vec![
            SConst(Register(1), String::from("marf")),
            SConst(Register(2), String::from("tacos")),
            SConst(Register(3), String::from("marf")),
        ];

        assert_eq!(walker.instructions, expected);
    }

    #[test]
    fn test_visit_block_populates_instructions() {
        let block = "{ int a = '🏯'; dump(a); }";
        let mut tree = lpc_parser::BlockParser::new()
            .parse(&Context::default(), LexWrapper::new(block))
            .unwrap();

        let mut scope_walker = ScopeWalker::default();
        let _ = scope_walker.visit_block(&mut tree);

        let context = scope_walker.into_context();
        let mut walker = CodegenWalker::new(context);
        let _ = walker.visit_block(&mut tree);

        let expected = vec![
            IConst(Register(1), 127983),
            Call {
                name: String::from("dump"),
                num_args: 1,
                initial_arg: Register(1),
            },
        ];

        assert_eq!(walker.instructions, expected);
    }

    #[test]
    fn test_visit_function_def_populates_the_data() {
        let mut scope_walker = ScopeWalker::default();
        let _walker = CodegenWalker::default();
        let call = "int main(int i) { return i + 4; }";
        let tree = lpc_parser::DefParser::new()
            .parse(&Context::default(), LexWrapper::new(call))
            .unwrap();

        let mut node = if let AstNode::FunctionDef(node) = tree {
            node
        } else {
            panic!("Didn't receive a function def?");
        };

        let _ = scope_walker.visit_function_def(&mut node);

        let mut context = scope_walker.into_context();
        context.scopes.goto_root();

        let mut walker = CodegenWalker::new(context);
        let _ = walker.visit_function_def(&mut node);

        let expected = vec![
            IConst(Register(2), 4),
            IAdd(Register(1), Register(2), Register(3)),
            RegCopy(Register(3), Register(0)),
            Ret,
        ];

        assert_eq!(walker.instructions, expected);

        let address: Address = 0;

        let sym = FunctionSymbol {
            name: "main".to_string(),
            num_args: 1,
            num_locals: 2,
            address,
        };

        assert_eq!(walker.functions.get(&sym).unwrap(), &address);
    }

    #[test]
    fn test_visit_function_def_handles_ellipses() {
        let mut scope_walker = ScopeWalker::default();
        let _walker = CodegenWalker::default();
        let call = "int main(int i, ...) { return argv; }";
        let tree = lpc_parser::DefParser::new()
            .parse(&Context::default(), LexWrapper::new(call))
            .unwrap();

        let mut node = if let AstNode::FunctionDef(node) = tree {
            node
        } else {
            panic!("Didn't receive a function def?");
        };

        let _ = scope_walker.visit_function_def(&mut node);

        let mut context = scope_walker.into_context();
        context.scopes.goto_root();

        let mut walker = CodegenWalker::new(context);
        let _ = walker.visit_function_def(&mut node);

        let expected = vec![RegCopy(Register(2), Register(0)), Ret];

        assert_eq!(walker.instructions, expected);
    }

    #[test]
    fn visit_return_populates_the_instructions() {
        let mut walker = CodegenWalker::default();

        let mut node = ReturnNode::new(Some(ExpressionNode::from(IntNode::new(666))));
        let _ = walker.visit_return(&mut node);

        let expected = vec![
            IConst(Register(1), 666),
            RegCopy(Register(1), Register(0)),
            Ret,
        ];

        assert_eq!(walker.instructions, expected);

        /* === */

        let mut walker = CodegenWalker::default();
        let mut node = ReturnNode::new(None);
        let _ = walker.visit_return(&mut node);

        let expected = vec![Ret];

        assert_eq!(walker.instructions, expected);
    }

    #[test]
    fn test_decl_sets_scope_and_instructions() {
        let call = "int foo = 1, *bar = ({ 56 })";
        let mut tree = lpc_parser::DeclParser::new()
            .parse(&Context::default(), LexWrapper::new(call))
            .unwrap();

        let mut scope_walker = ScopeWalker::default();
        let _ = scope_walker.visit_decl(&mut tree);

        let context = scope_walker.into_context();
        let mut walker = CodegenWalker::new(context);
        let _ = walker.visit_decl(&mut tree);

        let expected = vec![
            IConst1(Register(1)),
            GStore(Register(1), Register(1)),
            IConst(Register(2), 56),
            AConst(Register(3), vec![Register(2)]),
            GStore(Register(3), Register(2)),
        ];

        assert_eq!(walker.instructions, expected);

        let scope = walker.context.scopes.current().unwrap();
        assert_eq!(
            scope.lookup("foo").unwrap(),
            Symbol {
                name: String::from("foo"),
                type_: LpcType::Int(false),
                static_: false,
                location: Some(Register(1)),
                scope_id: 0,
                span: Some(Span {
                    file_id: 0,
                    l: 4,
                    r: 11
                })
            }
        );
        assert_eq!(
            scope.lookup("bar").unwrap(),
            Symbol {
                name: String::from("bar"),
                type_: LpcType::Int(true),
                static_: false,
                location: Some(Register(2)),
                scope_id: 0,
                span: Some(Span {
                    file_id: 0,
                    l: 13,
                    r: 25
                })
            }
        );
    }

    mod test_visit_var {
        use super::*;

        #[test]
        fn test_visit_var_loads_the_var_and_sets_the_result_for_globals() {
            let mut context = Context::default();
            context.scopes.push_new();

            let mut walker = CodegenWalker::new(context);

            insert_symbol(
                &mut walker,
                Symbol {
                    name: "marf".to_string(),
                    type_: LpcType::Int(false),
                    static_: false,
                    location: Some(Register(666)),
                    scope_id: 0,
                    span: None,
                },
            );
            // push a local scope with a matching variable in a different location
            walker.context.scopes.push_new();
            insert_symbol(
                &mut walker,
                Symbol {
                    name: "marf".to_string(),
                    type_: LpcType::Int(false),
                    static_: false,
                    location: Some(Register(222)),
                    scope_id: 1,
                    span: None,
                },
            );

            let mut node = VarNode {
                name: "marf".to_string(),
                span: None,
                global: true,
            };

            let _ = walker.visit_var(&mut node);
            assert_eq!(walker.current_result, Register(1)); // global loaded into r1

            let expected = vec![GLoad(Register(666), Register(1))];
            assert_eq!(walker.instructions, expected);
        }

        #[test]
        fn test_visit_var_sets_the_result_for_locals() {
            let mut context = Context::default();
            context.scopes.push_new();
            let mut walker = CodegenWalker::new(context);

            insert_symbol(
                &mut walker,
                // push a global marf to ensure we don't find it.
                Symbol {
                    name: "marf".to_string(),
                    type_: LpcType::Int(false),
                    static_: false,
                    location: Some(Register(444)),
                    scope_id: 0,
                    span: None,
                },
            );
            walker.context.scopes.push_new(); // push a local scope
            insert_symbol(
                &mut walker,
                Symbol {
                    name: "marf".to_string(),
                    type_: LpcType::Int(false),
                    static_: false,
                    location: Some(Register(666)),
                    scope_id: 1,
                    span: None,
                },
            );

            let mut node = VarNode::new("marf");

            let _ = walker.visit_var(&mut node);
            assert_eq!(walker.current_result, Register(666));

            let expected = vec![];
            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_visit_assignment {
        use super::*;

        #[test]
        fn test_populates_the_instructions_for_globals() {
            let mut context = Context::default();
            context.scopes.push_new();
            let mut walker = CodegenWalker::new(context);

            let sym = Symbol {
                name: "marf".to_string(),
                type_: LpcType::Int(false),
                static_: false,
                location: Some(Register(666)),
                scope_id: 0,
                span: None,
            };
            insert_symbol(&mut walker, sym);

            // push a different, local `marf`, to ensure that we don't find it for this assignment.
            walker.context.scopes.push_new();
            let sym = Symbol {
                name: "marf".to_string(),
                type_: LpcType::Int(false),
                static_: false,
                location: Some(Register(123)),
                scope_id: 1,
                span: None,
            };
            insert_symbol(&mut walker, sym);

            let mut node = AssignmentNode {
                lhs: Box::new(ExpressionNode::Var(VarNode {
                    name: "marf".to_string(),
                    span: None,
                    global: true,
                })),
                rhs: Box::new(ExpressionNode::Int(IntNode::new(-12))),
                span: None,
            };

            let _ = walker.visit_assignment(&mut node);
            assert_eq!(
                walker.instructions,
                [
                    IConst(Register(1), -12),
                    GLoad(Register(666), Register(2)),
                    RegCopy(Register(1), Register(2)),
                    GStore(Register(2), Register(666))
                ]
            );
        }

        #[test]
        fn test_populates_the_instructions_for_locals() {
            let mut context = Context::default();
            context.scopes.push_new();
            context.scopes.push_new();
            let mut walker = CodegenWalker::new(context);

            let sym = Symbol {
                name: "marf".to_string(),
                type_: LpcType::Int(false),
                static_: false,
                location: Some(Register(666)),
                scope_id: 1,
                span: None,
            };

            insert_symbol(&mut walker, sym);

            let mut node = AssignmentNode {
                lhs: Box::new(ExpressionNode::Var(VarNode::new("marf"))),
                rhs: Box::new(ExpressionNode::Int(IntNode::new(-12))),
                span: None,
            };

            let _ = walker.visit_assignment(&mut node);
            assert_eq!(
                walker.instructions,
                [
                    IConst(Register(1), -12),
                    RegCopy(Register(1), Register(666))
                ]
            );
        }

        #[test]
        fn test_populates_the_instructions_for_array_items() {
            let mut context = Context::default();
            context.scopes.push_new();
            context.scopes.push_new();
            let mut walker = CodegenWalker::new(context);

            let sym = Symbol {
                name: "marf".to_string(),
                type_: LpcType::Int(true),
                static_: false,
                location: Some(Register(666)),
                scope_id: 1,
                span: None,
            };

            insert_symbol(&mut walker, sym);

            let mut node = AssignmentNode {
                lhs: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::from(VarNode::new("marf"))),
                    r: Box::new(ExpressionNode::from(1)),
                    op: BinaryOperation::Index,
                    span: None,
                })),
                rhs: Box::new(ExpressionNode::from(-12)),
                span: None,
            };

            let _ = walker.visit_assignment(&mut node);
            assert_eq!(
                walker.instructions,
                [
                    IConst(Register(1), -12),
                    IConst1(Register(2)),
                    Store(Register(1), Register(666), Register(2))
                ]
            );
        }
    }

    #[test]
    fn test_visit_array_populates_the_instructions() {
        let mut walker = CodegenWalker::default();

        let mut arr = ArrayNode::new(vec![
            ExpressionNode::from(123),
            ExpressionNode::from("foo"),
            ExpressionNode::from(vec![ExpressionNode::from(666)]),
        ]);

        let _ = walker.visit_array(&mut arr);

        let expected = vec![
            IConst(Register(1), 123),
            SConst(Register(2), String::from("foo")),
            IConst(Register(3), 666),
            AConst(Register(4), vec![Register(3)]),
            AConst(Register(5), vec![Register(1), Register(2), Register(4)]),
        ];

        assert_eq!(walker.instructions, expected);
    }

    #[test]
    fn test_visit_comma_expression_populates_the_instructions() {
        let mut walker = CodegenWalker::default();

        let mut expr = CommaExpressionNode::new(vec![
            ExpressionNode::from(123),
            ExpressionNode::from("foo"),
            ExpressionNode::from(vec![ExpressionNode::from(666)]),
        ]);

        let _ = walker.visit_comma_expression(&mut expr);

        let expected = vec![
            IConst(Register(1), 123),
            SConst(Register(2), String::from("foo")),
            IConst(Register(3), 666),
            AConst(Register(4), vec![Register(3)]),
        ];

        assert_eq!(walker.instructions, expected);
        assert_eq!(walker.current_result, Register(4));
    }

    mod test_visit_var_init {
        use super::*;
        use crate::asm::instruction::Instruction::{FConst, MapConst};
        use decorum::Total;

        fn setup() -> CodegenWalker {
            let mut context = Context::default();
            context.scopes.push_new();
            context.scopes.push_new();
            CodegenWalker::new(context)
        }

        fn setup_var(type_: LpcType, walker: &mut CodegenWalker) {
            let sym = Symbol {
                location: Some(Register(1)),
                ..Symbol::new("marf", type_)
            };
            walker.register_counter.next(); // force-increment to mimic the scope walker
            insert_symbol(walker, sym);

            let mut node = VarInitNode {
                type_,
                name: "muffins".to_string(),
                value: Some(ExpressionNode::Var(VarNode::new("marf"))),
                array: false,
                global: false,
                span: None,
            };

            insert_symbol(walker, Symbol::from(&mut node.clone()));

            let _ = walker.visit_var_init(&mut node);
        }

        fn setup_literal(type_: LpcType, value: ExpressionNode, walker: &mut CodegenWalker) {
            let mut node = VarInitNode {
                type_,
                name: "muffins".to_string(),
                value: Some(value),
                array: false,
                global: false,
                span: None,
            };

            insert_symbol(walker, Symbol::from(&mut node));

            let _ = walker.visit_var_init(&mut node);
        }

        #[test]
        fn test_does_not_copy_mapping_literals() {
            let mut walker = setup();
            let pairs = vec![(ExpressionNode::from("foo"), ExpressionNode::from("bar"))];
            setup_literal(
                LpcType::Mapping(false),
                ExpressionNode::Mapping(MappingNode::new(pairs, None)),
                &mut walker,
            );

            let mut map = HashMap::new();
            map.insert(Register(1), Register(2));
            assert_eq!(
                walker.instructions,
                [
                    SConst(Register(1), String::from("foo")),
                    SConst(Register(2), String::from("bar")),
                    MapConst(Register(3), map)
                ]
            );
        }

        #[test]
        fn test_copies_mapping_vars() {
            let mut walker = setup();
            setup_var(LpcType::Mapping(false), &mut walker);

            assert_eq!(walker.instructions, [RegCopy(Register(1), Register(2))]);
        }

        #[test]
        fn test_does_not_copy_int_literals() {
            let mut walker = setup();
            setup_literal(
                LpcType::Int(false),
                ExpressionNode::Int(IntNode::new(123)),
                &mut walker,
            );

            assert_eq!(walker.instructions, [IConst(Register(1), 123)]);
        }

        #[test]
        fn test_copies_int_vars() {
            let mut walker = setup();
            setup_var(LpcType::Int(false), &mut walker);

            assert_eq!(walker.instructions, [RegCopy(Register(1), Register(2))]);
        }

        #[test]
        fn test_does_not_copy_float_literals() {
            let mut walker = setup();
            setup_literal(
                LpcType::Float(false),
                ExpressionNode::Float(FloatNode::new(123.0)),
                &mut walker,
            );

            assert_eq!(
                walker.instructions,
                [FConst(Register(1), Total::from(123.0))]
            );
        }

        #[test]
        fn test_copies_float_vars() {
            let mut walker = setup();
            setup_var(LpcType::Float(false), &mut walker);

            assert_eq!(walker.instructions, [RegCopy(Register(1), Register(2))]);
        }

        #[test]
        fn test_does_not_copy_string_literals() {
            let mut walker = setup();
            setup_literal(
                LpcType::Int(true),
                ExpressionNode::String(StringNode::new("foo")),
                &mut walker,
            );

            assert_eq!(
                walker.instructions,
                [SConst(Register(1), String::from("foo"))]
            );
        }

        #[test]
        fn test_copies_string_vars() {
            let mut walker = setup();
            setup_var(LpcType::String(false), &mut walker);

            assert_eq!(walker.instructions, [RegCopy(Register(1), Register(2))]);
        }

        #[test]
        fn test_does_not_copy_array_literals() {
            let mut walker = setup();
            setup_literal(
                LpcType::Int(true),
                ExpressionNode::Array(ArrayNode::new(vec![ExpressionNode::from(1234)])),
                &mut walker,
            );

            assert_eq!(
                walker.instructions,
                [
                    IConst(Register(1), 1234),
                    AConst(Register(2), vec![Register(1)])
                ]
            );
        }

        #[test]
        fn test_copies_array_vars() {
            let mut walker = setup();
            setup_var(LpcType::Int(true), &mut walker);

            assert_eq!(walker.instructions, [RegCopy(Register(1), Register(2))]);
        }

        #[test]
        fn copies_calls() {
            let mut walker = setup();

            let mut node = VarInitNode {
                type_: LpcType::Object(false),
                name: "muffins".to_string(),
                value: Some(ExpressionNode::Call(CallNode {
                    receiver: Box::new(None),
                    arguments: vec![ExpressionNode::from("/foo/bar.c")],
                    name: "clone_object".to_string(),
                    span: None,
                })),
                array: false,
                global: false,
                span: None,
            };

            insert_symbol(&mut walker, Symbol::from(&mut node.clone()));

            let _ = walker.visit_var_init(&mut node);

            assert_eq!(
                walker.instructions,
                [
                    SConst(Register(1), String::from("/foo/bar.c")),
                    Call {
                        name: String::from("clone_object"),
                        num_args: 1,
                        initial_arg: Register(1)
                    },
                    RegCopy(Register(0), Register(2))
                ]
            );
        }

        #[test]
        fn sets_up_globals() {
            let mut context = Context::default();
            context.scopes.push_new();
            let mut walker = CodegenWalker::new(context);

            let mut node = VarInitNode {
                type_: LpcType::Mixed(true),
                name: "arr".to_string(),
                value: Some(ExpressionNode::from(vec![
                    ExpressionNode::from(12),
                    ExpressionNode::from(4.3),
                    ExpressionNode::from("hello"),
                    ExpressionNode::from(vec![
                        ExpressionNode::from(1),
                        ExpressionNode::from(2),
                        ExpressionNode::from(3),
                    ]),
                ])),
                array: false,
                global: true,
                span: None,
            };

            insert_symbol(&mut walker, Symbol::from(&mut node.clone()));

            let mut node2 = VarInitNode {
                type_: LpcType::Mixed(true),
                name: "str".to_string(),
                value: Some(ExpressionNode::from("sup")),
                array: false,
                global: true,
                span: None,
            };

            insert_symbol(&mut walker, Symbol::from(&mut node.clone()));
            insert_symbol(&mut walker, Symbol::from(&mut node2.clone()));

            let _ = walker.visit_var_init(&mut node);
            let _ = walker.visit_var_init(&mut node2);

            let expected = vec![
                IConst(Register(1), 12),
                FConst(Register(2), 4.3.into()),
                SConst(Register(3), "hello".into()),
                IConst1(Register(4)),
                IConst(Register(5), 2),
                IConst(Register(6), 3),
                AConst(Register(7), vec![Register(4), Register(5), Register(6)]),
                AConst(
                    Register(8),
                    vec![Register(1), Register(2), Register(3), Register(7)],
                ),
                GStore(Register(8), Register(1)),
                SConst(Register(9), "sup".into()),
                GStore(Register(9), Register(2)),
            ];

            assert_eq!(walker.instructions, expected);
            assert_eq!(walker.global_counter.as_usize(), 2);
            assert_eq!(walker.global_init_registers, 9);
        }
    }

    mod test_visit_if {
        use super::*;
        use crate::asm::instruction::Instruction::{EqEq, Jmp, Jz};

        #[test]
        fn test_populates_the_instructions() {
            let mut walker = CodegenWalker::default();

            let mut node = IfNode {
                condition: ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::from(666)),
                    r: Box::new(ExpressionNode::from(777)),
                    op: BinaryOperation::EqEq,
                    span: None,
                }),
                body: Box::new(AstNode::Call(CallNode {
                    receiver: Box::new(None),
                    arguments: vec![ExpressionNode::from("true")],
                    name: "dump".to_string(),
                    span: None,
                })),
                else_clause: Box::new(Some(AstNode::Call(CallNode {
                    receiver: Box::new(None),
                    arguments: vec![ExpressionNode::from("false")],
                    name: "dump".to_string(),
                    span: None,
                }))),
                scope_id: None,
                span: None,
            };

            let _ = walker.visit_if(&mut node);

            let expected = vec![
                IConst(Register(1), 666),
                IConst(Register(2), 777),
                EqEq(Register(1), Register(2), Register(3)),
                Jz(Register(3), "if-else_0".into()),
                SConst(Register(4), String::from("true")),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(4),
                },
                Jmp("if-end_1".into()),
                SConst(Register(5), String::from("false")),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(5),
                },
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_visit_while {
        use super::*;
        use crate::asm::instruction::Instruction::{EqEq, Jmp, Jz};

        #[test]
        fn test_populates_the_instructions() {
            let mut walker = CodegenWalker::default();

            let mut node = WhileNode {
                condition: ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::from(666)),
                    r: Box::new(ExpressionNode::from(777)),
                    op: BinaryOperation::EqEq,
                    span: None,
                }),
                body: Box::new(AstNode::Call(CallNode {
                    receiver: Box::new(None),
                    arguments: vec![ExpressionNode::from("body")],
                    name: "dump".to_string(),
                    span: None,
                })),
                scope_id: None,
                span: None,
            };

            let _ = walker.visit_while(&mut node);

            let expected = vec![
                IConst(Register(1), 666),
                IConst(Register(2), 777),
                EqEq(Register(1), Register(2), Register(3)),
                Jz(Register(3), "while-end_1".into()),
                SConst(Register(4), String::from("body")),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(4),
                },
                Jmp("while-start_0".into()),
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_visit_do_while {
        use super::*;
        use crate::{
            asm::instruction::Instruction::{EqEq, Jnz},
            ast::do_while_node::DoWhileNode,
        };

        #[test]
        fn test_populates_the_instructions() {
            let mut walker = CodegenWalker::default();

            let mut node = DoWhileNode {
                condition: ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::from(666)),
                    r: Box::new(ExpressionNode::from(777)),
                    op: BinaryOperation::EqEq,
                    span: None,
                }),
                body: Box::new(AstNode::Call(CallNode {
                    receiver: Box::new(None),
                    arguments: vec![ExpressionNode::from("body")],
                    name: "dump".to_string(),
                    span: None,
                })),
                scope_id: None,
                span: None,
            };

            let _ = walker.visit_do_while(&mut node);

            let expected = vec![
                SConst(Register(1), String::from("body")),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
                IConst(Register(2), 666),
                IConst(Register(3), 777),
                EqEq(Register(2), Register(3), Register(4)),
                Jnz(Register(4), "do-while-start_0".into()),
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_visit_for {
        use super::*;
        use crate::{
            asm::instruction::Instruction::{ISub, Jmp, Jz},
            ast::for_node::ForNode,
        };

        #[test]
        fn populates_the_instructions() {
            let var = VarNode {
                name: "i".to_string(),
                span: None,
                global: false,
            };

            let mut node = ForNode {
                initializer: Box::new(Some(AstNode::VarInit(VarInitNode {
                    type_: LpcType::Int(false),
                    name: "i".to_string(),
                    value: Some(ExpressionNode::from(10)),
                    array: false,
                    global: false,
                    span: None,
                }))),
                condition: Some(ExpressionNode::Var(var.clone())),
                incrementer: Some(ExpressionNode::Assignment(AssignmentNode {
                    lhs: Box::new(ExpressionNode::Var(var.clone())),
                    rhs: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                        l: Box::new(ExpressionNode::Var(var.clone())),
                        r: Box::new(ExpressionNode::from(1)),
                        op: BinaryOperation::Sub,
                        span: None,
                    })),
                    span: None,
                })),
                body: Box::new(AstNode::Block(BlockNode {
                    body: vec![AstNode::Call(CallNode {
                        receiver: Box::new(None),
                        arguments: vec![ExpressionNode::Var(var)],
                        name: "dump".to_string(),
                        span: None,
                    })],
                    scope_id: None,
                })),
                scope_id: None,
                span: None,
            };

            let mut scope_walker = ScopeWalker::default();
            let _ = scope_walker.visit_for(&mut node);

            let context = scope_walker.into_context();
            let mut walker = CodegenWalker::new(context);

            let _ = walker.visit_for(&mut node).unwrap();

            let expected = vec![
                IConst(Register(1), 10),
                Jz(Register(1), "for-end_1".into()),
                Call {
                    name: String::from("dump"),
                    num_args: 1,
                    initial_arg: Register(1),
                },
                IConst1(Register(2)),
                ISub(Register(1), Register(2), Register(3)),
                RegCopy(Register(3), Register(1)),
                Jmp("for-start_0".into()),
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_visit_ternary {
        use super::*;
        use crate::{
            asm::instruction::Instruction::{Jmp, Jz, Lte},
            ast::ternary_node::TernaryNode,
        };

        #[test]
        fn populates_the_instructions() {
            let mut node = TernaryNode {
                condition: Box::new(ExpressionNode::BinaryOp(BinaryOpNode {
                    l: Box::new(ExpressionNode::from(2)),
                    r: Box::new(ExpressionNode::from(3)),
                    op: BinaryOperation::Lte,
                    span: None,
                })),
                body: Box::new(ExpressionNode::from(666)),
                else_clause: Box::new(ExpressionNode::from(777)),
                span: None,
            };

            let mut walker = CodegenWalker::new(Context::default());

            let _ = walker.visit_ternary(&mut node).unwrap();

            let expected = vec![
                IConst(Register(2), 2),
                IConst(Register(3), 3),
                Lte(Register(2), Register(3), Register(4)),
                Jz(Register(4), "ternary-else_0".into()), // jump to else
                IConst(Register(5), 666),
                RegCopy(Register(5), Register(1)),
                Jmp("ternary-end_1".into()), // jump to end
                IConst(Register(6), 777),
                RegCopy(Register(6), Register(1)),
            ];

            assert_eq!(walker.instructions, expected);
        }
    }

    mod test_to_program {
        use super::*;

        #[test]
        fn sets_num_globals() {
            let code = r##"
            int i = 123, j;
            mixed *arr = ({ "foo", "bar", "baz", ({ "quux", 0 }) });
            string asdf = "asdf";
            string b;
        "##;

            let program = walk_prog(code).to_program().expect("failed to compile");
            assert_eq!(program.num_globals, 6)
        }

        #[test]
        fn sets_num_init_registers() {
            let code = r##"
            int i = 123, j;
            mixed *arr = ({ "foo", "bar", "baz", ({ "quux", 0 }) });
            string asdf = "asdf";
            string b;
        "##;

            let program = walk_prog(code).to_program().expect("failed to compile");
            assert_eq!(program.num_init_registers, 11)
        }

        #[test]
        fn reserves_enough_global_registers_when_create_returns_non_void() {
            let code = r##"
                int create() {
                    dump("sup dawg");
                    int b = 123;
                    return b;
                }
            "##;

            let program = walk_prog(code).to_program().expect("failed to compile");
            assert_eq!(program.num_init_registers, 1)
        }
    }

    fn insert_symbol(walker: &mut CodegenWalker, symbol: Symbol) {
        if let Some(node_id) = walker.context.scopes.current_id {
            walker
                .context
                .scopes
                .get_mut(node_id)
                .unwrap()
                .insert(symbol)
        } else {
            panic!("No current scope to insert the symbol into.")
        }
    }
}
