[package]
name = "lpc-rs-core"
version = "0.1.0"
authors = ["mpd <mpd@jesters-court.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decorum = "0.3.1"
modular-bitfield = "0.11.2"
serde = { version = "1.0.123", features = ["derive"] }
